# Generated by Django 5.2.7 on 2025-12-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindspaceapp', '0002_add_phone_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='anonymous', max_length=100)),
                ('mood', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
