# Generated by Django 5.2.7 on 2025-12-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindspaceapp', '0003_mood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mood',
        ),
    ]
